# Site settings
title: Anthony Keating
email: keatinganthony@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Full stack developer since 2015. Based in NYC.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://keatinganthony.com" # the base hostname & protocol for your site
twitter_username: anthonysays
github_username: anthonyk1225
linkedin_username: keatinganthony

# Build settings
markdown: kramdown
