# Site settings
title: Anthony Keating
email: keatinganthony@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, my name's Anthony. I'm 28, and currently living in New York, working as a software developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://keatinganthony.com" # the base hostname & protocol for your site
twitter_username: anthonysays
github_username:  anthonyk1225
linkedin_username: keatinganthony

# Build settings
markdown: kramdown
