# Site settings
title: Welcome to Middle Earth
email: anthonyk1225@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, my name is Anthony! I'm a 26 year old from New York. I enjoy crossfit,
  coding, video games, and good music. This blog will be dedicated to documenting
  my journey at Byte Academy for it's February '15' cohort.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: anthonysays
github_username:  anthonyk1225

# Build settings
markdown: kramdown
